IDEA_SCHEMA = {
    "type": "OBJECT",
    "properties": {
        # --- THE CAPPED RESPONSE ---
        "formatted_sms": {
            "type": "STRING",
            "description": "The final <160 char string: [Reaction] Pitch: [Pitch]. Effort: [X] | $$: [Y]. Stack: [Z].",
        },
        # --- STRUCTURED DATA FOR FIRESTORE ---
        "ai_reaction": {
            "type": "STRING",
            "description": "The unique one-sentence reaction generated by the AI.",
        },
        "one_sentence_pitch": {"type": "STRING", "description": "Max 50 characters."},
        "estimated_complexity": {"type": "STRING", "enum": ["Low", "Medium", "High", "Extreme"]},
        "monetization_potential": {"type": "INTEGER", "description": "1-5 scale."},
        "tech_stack_suggestions": {"type": "STRING", "description": "3 words max."},
        "core_problem": {"type": "STRING"},
    },
    "required": [
        "formatted_sms",
        "ai_reaction",
        "one_sentence_pitch",
        "estimated_complexity",
        "monetization_potential",
    ],
}
